<?php
/**
 * Category sidebar
 *
 * @var $block Sebwite\Sidebar\Block\Sidebar
 */
$isEnabled     = $block->isEnabled();
$titleText     = $block->getTitleText();
$isOpenOnLoad  = $block->isOpenOnLoad();
$categories    = $block->getCategories();

function getChildCategoryView($block, $category, $html = '', $level = 1)
{
    // Check if category has children
    if ( $category->hasChildren() )
    {

        $childCategories = $block->getSubcategories($category);

        if (is_object($childCategories) && count($childCategories) > 0 )
        {

            $html .= '<ul class="o-list o-list--unstyled">';

            // Loop through children categories
            foreach ( $childCategories as $childCategory )
            {

                $html .= '<li class="level' . $level . ($block->isActive($childCategory) ? ' active' : '') . '">';
                $html .= '<a href="' . $block->getCategoryUrl($childCategory) . '" title="' . $childCategory->getName() . '" class="' . ($block->isActive($childCategory) ? 'is-active' : '') . '">' . $childCategory->getName() . '</a>';

                if ( $childCategory->hasChildren() )
                {
                    if ( $block->isActive($childCategory) )
                    {
                        $html .= '<span class="expanded"><i class="fa fa-minus"></i></span>';
                    }
                    else
                    {
                        $html .= '<span class="expand"><i class="fa fa-plus"></i></span>';
                    }
                }

                if ( $childCategory->hasChildren() )
                {
                    $html .= getChildCategoryView($block, $childCategory, '', ($level + 1));
                }

                $html .= '</li>';
            }
            $html .= '</ul>';
        }
    }

    return $html;
}

if ($isEnabled) {
?>

    <h3><?= $titleText; ?></h3>
    <ul class="o-list">

    <?php
    // Loop through categories
    foreach ( $categories as $category ) :
        ?>
        <li class="level0<?php echo($block->isActive($category) ? ' active' : ''); ?>">
            <a href="<?php echo $block->getCategoryUrl($category); ?>" title="<?php echo $category->getName(); ?>" class="<?php echo($block->isActive($category) ? ' active' : ''); ?>">
                <?php echo $category->getName(); ?>
            </a>
            <?php if ( $category->hasChildren() ) : ?>
                <span class="expand"><?php echo $block->isActive($category) ? '<i class="fa fa-minus"></i>' : '<i class="fa fa-plus"></i>'; ?></span>
            <?php endif; ?>

            <?php echo getChildCategoryView($block, $category); ?>
        </li>
    <?php endforeach; ?>
    </ul>
<?php if ($isOpenOnLoad) { ?>
    <script>
        require(['jquery', 'sidebarmodule'], function($) {
            $('.is-active').parents('ul').css('display','block');
            $('.is-active').parents('li').addClass('active');
            $('.is-active').parents('li').find('> span i').removeClass('fa-plus').addClass('fa-minus');
        });
    </script>
<?php } else { ?>
    <script>
        require(['jquery', 'sidebarmodule'], function($) {});
    </script>
<?php }
} ?>